name: GitHub Actions Demo
on: [push]
jobs:
  Unit Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting unit tests execution on ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: '14.17.5'
      - run: npm run test
