name: Triangle Classification
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting unit tests execution on ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: '14.17.5'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test
  deploy-serverless:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting AWS Serverless Deploy"
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install NPM
        run: sudo apt update -y && sudo apt install nodejs npm -y

      - name: Install Dependencies
        run: npm install

    needs: unit-tests
